import { promises as fs } from 'fs';
import { Formatter } from '../types';
import { formatContent } from './formatUtils';

/**
 * Generates TypeScript type definitions for icon names.
 */
export const generateTypes = async ({
  names,
  outputPath,
  formatter,
  pathToFormatterConfig,
}: {
  names: string[];
  outputPath: string;
  formatter?: Formatter;
  pathToFormatterConfig?: string;
}) => {
  const typeContent = [
    '// This file is generated by spriteify plugin',
    'export const iconNames = [',
    ...names.map((name) => `  "${name}",`),
    '] as const;',
    'export type IconName = typeof iconNames[number];',
  ].join('\n');

  const formattedTypes = await formatContent(typeContent, formatter, pathToFormatterConfig, 'ts');
  await fs.writeFile(outputPath, formattedTypes, 'utf8');
};
